import Link from "next/link";
import { ArrowLeft, Fuel, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { LandingFooter } from "@/components/landing/landing-footer";

export const metadata = {
  title: "Operational Disclaimer | Easy Manager",
  description: "Operational and financial calculation disclaimer for Easy Manager fuel station register.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Mini header */}
      <header className="border-b border-border/60 bg-background/95 backdrop-blur-xs sticky top-0 z-40">
        <div className="mx-auto flex h-16 w-full max-w-5xl items-center justify-between px-4 sm:px-6">
          <Link href="/" className="flex items-center gap-2 font-semibold text-sm">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary text-primary-foreground">
              <Fuel className="h-3.5 w-3.5" />
            </div>
            <span>Easy Manager</span>
          </Link>
          <Button asChild variant="ghost" size="sm" className="gap-1.5 text-xs">
            <Link href="/">
              <ArrowLeft className="h-3.5 w-3.5" />
              <span>Back to home</span>
            </Link>
          </Button>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 mx-auto w-full max-w-4xl px-4 sm:px-6 py-12 sm:py-16">
        <div className="space-y-4 border-b border-border/60 pb-8">
          <div className="inline-flex items-center gap-2 rounded-full border border-amber-500/30 bg-amber-500/10 px-3 py-1 text-xs font-semibold text-amber-700 dark:text-amber-400">
            <AlertCircle className="h-3.5 w-3.5" />
            Operational Notice
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-foreground">
            Operational Disclaimer
          </h1>
          <p className="text-sm text-muted-foreground">
            Last updated: September 16, 2026
          </p>
        </div>

        <div className="mt-8 space-y-8 text-sm leading-relaxed text-muted-foreground">
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-foreground">1. Nature of the Software</h2>
            <p>
              Easy Manager is an internal digital operating register and calculation tool designed to assist petrol pump owners and forecourt managers with daily shift record-keeping. It is intended to simplify meter reading entries, sales volume calculations, dealer margin tracking, and operating cost summaries.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-foreground">2. Not Official Statutory Accounting or Tax Software</h2>
            <p>
              Easy Manager is <strong className="text-foreground">not</strong> a certified statutory accounting package, GST e-invoicing portal, or automated tax return filing system. The financial reports, RO gross margin figures, and net profitability calculations generated by Easy Manager are managerial aids for internal visibility and operational control. They do not replace audited books of accounts or official statutory filings prepared by licensed Chartered Accountants.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-foreground">3. Physical Reconciliation &amp; Stock Loss</h2>
            <p>
              Calculated figures depend entirely on accurate user input of physical dispensing unit (DU) totalizers, applicable selling rates, dealer margins, and operating expenses. Easy Manager does not automatically calibrate physical dispensing pumps, verify underground tank dip levels, or calculate temperature-adjusted evaporative losses unless explicitly documented in future modules. Station owners remain solely responsible for forecourt calibration and regulatory compliance.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-foreground">4. Oil Marketing Company Independence</h2>
            <p>
              Easy Manager is an independent software tool and is not officially affiliated with, endorsed by, or integrated into the proprietary automation networks of Indian Oil Corporation Limited (IOCL), Bharat Petroleum Corporation Limited (BPCL), Hindustan Petroleum Corporation Limited (HPCL), or any other oil marketing company.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-foreground">5. Limitation of Liability</h2>
            <p>
              Under no circumstances shall Easy Manager or its creators be held liable for commercial decisions, financial discrepancies, dealer commission changes by oil companies, cash reconciliation shortages, or regulatory non-compliance arising from the use of this software.
            </p>
          </section>
        </div>
      </main>

      <LandingFooter />
    </div>
  );
}
